name: rapi_car_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^1.0.0
  flat_icons_flutter: ^1.0.2
  flutter_svg: ^0.18.1
  flutter_statusbarcolor: ^0.2.3
  carousel_slider: ^2.2.1
  shared_preferences: ^0.5.10
  rxdart: ^0.24.1
  http: ^0.12.2
  provider: ^4.3.2+2
  path_provider: ^1.6.14
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.2.1
  flutter_swiper: ^1.1.6
  image_picker: ^0.6.7+11
  flutter_map: ^0.10.1+1
  geolocator: ^6.1.13
  permission_handler: ^5.0.1+1
  flutter_bloc: ^6.1.1
  google_maps_flutter: ^1.0.10
  dio: ^3.0.10
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.11.0
  flutter_credit_card: ^0.1.4
  stripe_payment: ^1.0.9
  get_it: ^5.0.1
  flutter_secure_storage: ^3.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/backgroun_location.png
  - assets/images/background-2.png
  - assets/images/background.png
  - assets/images/car-door.png
  - assets/images/loading.gif
  - assets/images/location_mark.png
  - assets/images/no-image.jpg
  - assets/data/
  - assets/images/
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  fonts:
  - assets/fonts
