// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: rapi_car_app
  static const package = "rapi_car_app";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/backgroun_location.png
  // ignore: non_constant_identifier_names
  final backgroun_location = const AssetResource(
      "assets/images/backgroun_location.png",
      packageName: null);

  /// asset: assets/images/background-2.png
  // ignore: non_constant_identifier_names
  final background_2 =
      const AssetResource("assets/images/background-2.png", packageName: null);

  /// asset: assets/images/background.png
  // ignore: non_constant_identifier_names
  final background =
      const AssetResource("assets/images/background.png", packageName: null);

  /// asset: assets/images/car-door.png
  // ignore: non_constant_identifier_names
  final car_door =
      const AssetResource("assets/images/car-door.png", packageName: null);

  /// asset: assets/images/loading.gif
  // ignore: non_constant_identifier_names
  final loading_gif =
      const AssetResource("assets/images/loading.gif", packageName: null);

  /// asset: assets/images/location_mark.png
  // ignore: non_constant_identifier_names
  final location_mark =
      const AssetResource("assets/images/location_mark.png", packageName: null);

  /// asset: assets/images/no-image.jpg
  // ignore: non_constant_identifier_names
  final no_image_jpg =
      const AssetResource("assets/images/no-image.jpg", packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: assets/images/master_card.svg
  // ignore: non_constant_identifier_names
  final master_card =
      const AssetResource("assets/images/master_card.svg", packageName: null);

  /// asset: assets/images/visa_card.svg
  // ignore: non_constant_identifier_names
  final visa_card =
      const AssetResource("assets/images/visa_card.svg", packageName: null);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/backgroun_location.png
  // ignore: non_constant_identifier_names
  AssetImage backgroun_location() {
    return AssetImage(asset.backgroun_location.keyName);
  }

  /// asset: assets/images/background-2.png
  // ignore: non_constant_identifier_names
  AssetImage background_2() {
    return AssetImage(asset.background_2.keyName);
  }

  /// asset: assets/images/background.png
  // ignore: non_constant_identifier_names
  AssetImage background() {
    return AssetImage(asset.background.keyName);
  }

  /// asset: assets/images/car-door.png
  // ignore: non_constant_identifier_names
  AssetImage car_door() {
    return AssetImage(asset.car_door.keyName);
  }

  /// asset: assets/images/loading.gif
  // ignore: non_constant_identifier_names
  AssetImage loading_gif() {
    return AssetImage(asset.loading_gif.keyName);
  }

  /// asset: assets/images/location_mark.png
  // ignore: non_constant_identifier_names
  AssetImage location_mark() {
    return AssetImage(asset.location_mark.keyName);
  }

  /// asset: assets/images/no-image.jpg
  // ignore: non_constant_identifier_names
  AssetImage no_image_jpg() {
    return AssetImage(asset.no_image_jpg.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: assets/images/master_card.svg
  // ignore: non_constant_identifier_names
  AssetSvg master_card({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.master_card.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/visa_card.svg
  // ignore: non_constant_identifier_names
  AssetSvg visa_card({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.visa_card.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
